name = "ChemicalBuffers"
uuid = "7aa63eb5-5604-4e91-88e8-d4e232704c30"
authors = ["Thomas Poulsen"]
version = "0.1.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
